### ISSUE TITLE
License for the python code?

### ISSUE THREAD

**Issue by ghost** [PresidentKevvol/YorkCSClassList#4]
Hi,

I wanted to use your code for generating course dependency website for different universities (just University of Waterloo for now but I have friends at Laurier so).

I realized that you did not include separate license file or specified license as part of the source code.

I was wondering if I may assume that your works are in public domain or not.

Regards,

**Comment by unforgettableid** [comment]
Hi @kafka64!

Eight months have passed, and there hasn't been any reply from @PresidentKevvol.

You might want to try contacting him via [Discord](https://www.reddit.com/r/yorku/comments/16i1t8i/emptyrooms_have_been_updated_with_this_years_data/), [email](https://coursedelta.yorku.dev/#:~:text=To%20report%20a%20problem/mistake%2C%20email%20to%20ssadc.atyork%40gmail.com), or [Reddit](https://www.reddit.com/user/import_torch-nn/submitted?sort=new) instead.  In case you try that and there's still no reply, maybe try again during York's winter break (in late December) or even once the winter semester ends (in May).

I looked at [the list of closed pull requests](https://github.com/PresidentKevvol/YorkCSClassList/pulls?q=).  At least @joshua-dors might also have to agree to relicensing, thanks to his generous CSS contributions.

The sooner the relicensing gets done, the easier it might be.  Over time, projects can accumulate contributions from more and more people.  Each of these people might have to eventually agree to the relicensing.

Please reply here and let us know what they told you.

**Comment by PresidentKevvol** [comment]
Hi, thanks for the support and your patience waiting on my response.

To answer your questions:
1. I shall add an MIT license to this project.
2. I have spoken to @joshua-dors in private after the PR asking how he would like to be credited, he have stated he does not mind about attribution. In any case a permissive licence such as MIT should be compatible with that personal accordance.

**Comment by unforgettableid** [comment]
@PresidentKevvol:  I see the new license file is up.  Fantastic!

@kafka64:  Of course you can create a permanent fork the project if you want.  But, if it's not too much extra work, it might be interesting if you could send all your changes back here as a pull request.  Maybe eventually there could be one single codebase which handles course prerequisite tree generation for many schools.

**Comment by ghost** [comment]
Thank you for getting back to me and providing permissive license. I archived the repo some time ago but I will unarchive it to add the license soon.

I will also credit joshua-dors in my page. I did not know who beside PresidentKevvol was involved in this project.

Although I did not publish it yet, I was thinking of refactoring the python code to enable different sorting strategy (so it makes sense for other universities where course code may be double, two or three digits). I will open PR if you want to support other schools.

Closing this one for now as license issue has been resolved.
